#+include: ../head.org
#+latex_class: elsarticle
#+latex_class_options:[5p]
#+options: title:nil author:nil
#+title: BIPARTITE GRAPHS MATCHING IN CONSTRUCTION RESOURCES CONFIGURATION
#+Author: Xiaoyun Yu
#+BEGIN_abstract
abstract
#+END_abstract
#+BEGIN_keyword
Matching, Hydraulic construction project, Weighted Bipartite Graph
#+END_keyword
#+include: ../authors.org
* Introduction
Huge  hydraulic construction projects are one of the most complex work in organizing and management because of thousands of works and resources matching. The complicated organization work also imply in those work always located in a sharp space. To enlarge the work efficiency and lower the construction cost, largely equipments and resources usage is the fatal requirement of construction management. In this paper, a bipartite matching between equipments and jobs is proposed.
In the resources( including machines, equipments, materials etc)  allocation process, each resource could be allocated to different work, but at the same time, a resource only assign to one task simultaneously.
In a construction site, a resources configuration has been depicted prior construct, but during the construction process, all configured resources need to be allocated refer to construction job accomplishment.  

matching -> resource -> efficiency-> matching algorithm
bipartite graph-> matching 

Hungarian algorithm
Augmenting path, Alternating path

Resources configuration is prefer to be known as allocate each resource to different direction. and lead to full load of equipments and to avoid over load or less load.
that's to say, we can leveling the resource allocation to the maximum probabilityt.
** The purpose of the model
This model only works for a machine can do different work at the same time.

Construction resources management is vital important aspect for huge hydraulic projects, DING Jiyong cite:DINGJiyong2013 gave a approach on multi-resources leveling optimization under conditions of matching construction, they use resources entropy to describe leveling degree, and quantify the importance, consumption time distribution and matching degreee, an optimized model proposed to enlarge the leveling of resources allocation.
Perfection in matching that cost resources too, the cost of matching cite:Brazil2016   Hiyassat cite:Hiyassat2001 proposed a minimum matrix method that leveling resources.   
Lying idle is a sort of phenomenon that existed in construction site because of lack of resources arrangement and configuration or allocation, many resources are waste in the condition of lying idle, properly construction organizing and resources management could avoid lying idle in construction site.  
* Methodology
** weighted matching

** Basic hypothesis
This model basis on the following hypothesis:
1. All the same equipments has the same work ability.
2. There is only one equipment work on the work, and the work is only done bye the same equipment.
3. All works are linear works, there is no sequence for the work.
4. Task sequences are fixed constant in the model.
5. All allocating cost are ignored during the allocation process.
6. All other relationship between resources are not concerned.
** Model
*** Matching
 Suppose that we have a collection of $n$ equipments perform the work, and a collection of $n$ tasks which need to be perform by equipments. Suppose for the sake of argument that these equipments and tasks form two disjoint subsets $M$ and $F$ of the Euclidean plane $R^2$. Suppose also that we have a cost function c: $R2 \times R2 \rightarrow[0, \infty)$, so that $c(x, y)$ is the cost of work on $x$ by $y$. For simplicity, we ignore the time taken to other communication. We also assume that each equipment can do only one task (no splitting of work) and that each task requires precisely one equipment to be in operation (tasks cannot work at half or double-capacity). Having made the above assumptions, a work plan is a bijection $T:M \rightarrow F$. In other words, each equipment $m \in M$ supplies precisely one task $T(m) \in F$ and each task done by precisely one equipment. We wish to find the optimal work plan, the plan $T$ whose total cost
 #+BEGIN_LaTeX
 \begin{equation}
   \label{eq:sum-1}
   c(T):=\sum_{{m\in M}}c(m,T(m))
 \end{equation}
 #+END_LaTeX
 equation ref:eq:sum-1 is the least of all possible work plans from $M$ to $F$. This motivating special case of the transportation problem is an instance of the assignment problem. More specifically, it is equivalent to finding a cite:Ahn2015 minimum weight matching in a bipartite graph.
 The matching polynomial is:
 Let $G$ be a graph with $n$ vertices and let $M_k$ be the number of $k$-edge matchings, we notation of matching is:
 #+BEGIN_LaTeX
 \begin{equation}
   \label{eq:matchingpolynomial}
   m_G(x):=\sum_{k\geq}m_kx^k.
 \end{equation}
 #+END_LaTeX
 where $k$ is the number of edges.

** Bipartite graph theory
** Assignment problem
The assignment problem is one of the fundamental combinatorial optimization problems in the branch of optimization or operations research in mathematics. It consists of finding a maximum weight matching (or minimum weight perfect matching) in a weighted bipartite graph.
The problem instance has a number of agents and number of tasks. Any agent can be assigned to perform any task, incurring some cost that may vary depending on the agent-task assignment. It is required to perform all tasks by assigning exactly one agent to each task and exactly one task to each agent in such a way that the total cost of the assignment is minimized.
*** formula
The formal definition of the assignment problem (or linear assignment problem) is
Given two sets, $A$ and $T$, of equal size, together with a weight function $C : A \times T \rightarrow R$. Find a bijection $f : A \rightarrow T$ such that the cost function:
#+BEGIN_LaTeX
\begin{equation}
  \label{eq:costfunction}
\sum_{a\in A}C(a,f(a)) 
\end{equation}
#+END_LaTeX
is minimized.
Usually the weight function is viewed as a square real-valued matrix C, so that the cost function is written down as:
#+BEGIN_LaTeX
\begin{equation}
  \label{eq:costfunction-2}
\sum_{a\in A}C_{a,f(a)}
\end{equation}
#+END_LaTeX

The problem is "linear" because the cost function to be optimized as well as all the constraints contain only linear terms.
The problem can be expressed as a standard linear program with the objective function:
#+BEGIN_LaTeX
\begin{equation}
  \label{eq:assignment-main}
\sum_{i\in A}\sum_{j\in T}C(i,j)x_{ij}
\end{equation}
subject to the constraints:
\begin{equation}
  \label{eq:assignment-1}
\sum_{j\in T}x_{ij}=1{\text{ for }}i\in A,
\end{equation}
\begin{equation}
  \label{eq:assignment-2}
\sum_{i\in A}x_{ij}=1{\text{ for }}j\in T,
\end{equation}

\begin{equation}
  \label{eq:assignment-3}
x_{ij}\geq 0{\text{ for }i,j\in A,T. 
\end{equation}
#+END_LaTeX
The variable $x_{ij}$ represents the assignment of agent $i$ to task 
$j$, taking value 1 if the assignment is done and 0 otherwise. This formulation allows also fractional variable values, but there is always an optimal solution where the variables take integer values. This is because the constraint matrix is totally unimodular. The first constraint requires that every agent is assigned to exactly one task, and the second constraint requires that every task is assigned exactly one agent.
*** Weighted bipartite graph
*** Maximal matching problem
*** Definition
Let us call a function $y : (S\bigcup T) \rightarrow R$ a potential if $y(i) + y(j) \leq c(i, j)$ for each $i \in S, j \in T$ . The value of potential $y$ is $\sum_{v\in S \bigcup T}y(v)$. It can be seen that the cost of each perfect matching is at least the value of each potential. The Hungarian method finds a perfect matching and a potential with equal cost/value which proves the optimality of both. In fact it finds a perfect matching of tight edges: an edge $ij$ is called tight for a potential $y$ if $y(i) + y(j) = c(i, j)$. Let us denote the subgraph of tight edges by $G_y$. The cost of a perfect matching in $G_y$ (if there is one) equals the value of $y$.
#+BEGIN_LaTeX
\begin{equation}
  \label{eq:equation}
  
\end{equation}
#+END_LaTeX

* References
bibliography:./ResourcesMatching.bib
bibliographystyle:elsarticle-num
